name: Test, Format, Build and Release
on:
  workflow_dispatch:
jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features
  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
  build-and-release:
    needs: [test, formatting]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: 'Setup zigbuild'
        run: cargo install --locked cargo-zigbuild cargo-bump
      - name: Add must target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: -v --unreleased --bump --strip header --repository=${{ github.workspace }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      - name: 'Bump the version and Print It'
        run: |
          echo "next_version=${{ steps.git-cliff.outputs.version }}"
          export next_version_plain=$(echo ${{ steps.git-cliff.outputs.version }} | awk -F-v '{print $2}')
          echo "next-version-plain=$next_version_plain" >> $GITHUB_ENV
          cargo bump $next_version_plain
      - name: 'Print the changelog for ${{ steps.git-cliff.outputs.version }}'
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - name: Build
        run: cargo zigbuild --target x86_64-unknown-linux-musl --release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.git-cliff.outputs.version }}
          bodyFile: CHANGES.md
          prerelease: true
          artifacts: ./target/x86_64-unknown-linux-musl/release/generate-long-duration-jwt
          artifactContentType: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
